root = "/aulaga/"
testdata_dir = "testdata"
tmp_dir = "../tmp"

[build]
args_bin = []
#full_bin = "dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec /bin/aulaga --"
bin = "/bin/aulaga"
cmd = "go build -o /bin/aulaga /aulaga/cmd/"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true
poll = true # necessary when runnging docker-compose in windows

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false