version: '3'
services:
  backend:
    image: audav
    env_file: .env
    volumes:
      - ./:/aulaga
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - aulaga

networks:
  aulaga:
    driver: bridge