version: '3'
services:
  backend:
    image: audav
    env_file: .env
    volumes:
      - ./:/aulaga
    build:
      context: .
      dockerfile: Dockerfile.service
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
      - "40000:40000"
      - "80:80"
    networks:
      - aulaga

networks:
  aulaga:
    driver: bridge