FROM golang:1.21.6-alpine

WORKDIR /aulaga
COPY . .

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/cosmtrek/air@latest

RUN go mod download
RUN go build -o /bin/aulaga ./cmd

EXPOSE 8080
EXPOSE 40000
CMD ["air"]